#!/bin/bash
#BSUB -J homer
#BSUB -o /path/to/logfile/output-%J.out
#BSUB -e /path/to/logfile/error-%J.err

#bsub -q queue < /path/to/homermotifs.lsf


findMotifsGenome.pl /path/to/bedfile.bed hg38 /path/to/output
